import {NextRequest,NextResponse} from "next/server";
import {getSheetRanges} from "@/lib/google-sheets";

const SALES:Record<string,string>={"2025":"1NnRW70VyrtV8c89_M08gTnOGbtzeldSy8gL-gm4GjJ0","2026":"151Qfrz3RZnDMgZjKOPt5s_aS-zscSiOTCWodbUDWM1k"};
const STORES=["M117","M118","M124","M127","M217","M227","M238","M255","M264"];
function num(v:unknown){if(typeof v==="number")return Number.isFinite(v)?v:0;const x=Number(String(v??"").replace(/[^0-9.-]/g,""));return Number.isFinite(x)?x:0}
function dateKey(v:unknown){if(typeof v==="number"&&v>20000){const d=new Date(Date.UTC(1899,11,30)+v*86400000);return d.toISOString().slice(0,10)}const s=String(v??"").trim();let m=s.match(/^(\d{2})[-/](\d{2})[-/](\d{4})$/);if(m)return `${m[3]}-${m[2]}-${m[1]}`;m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:""}
function lob(v:unknown){const x=String(v??"").trim().toUpperCase().replace(/\s+/g," ");if(x==="IPHONE")return"iPhone";if(x==="IPAD")return"iPad";if(x==="MAC"||x==="MACBOOK")return"Mac";if(x==="APPLE WATCH"||x==="WATCH")return"Apple Watch";return""}
export async function GET(req:NextRequest){const year=req.nextUrl.searchParams.get("year")||"2026";if(!SALES[year])return NextResponse.json({error:"Tahun tidak valid"},{status:400});const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Google Sheets belum dikonfigurasi"},{status:503});try{const data=await getSheetRanges(SALES[year],STORES.map(c=>`'${c}'!A:O`),email,key);const rows:any[]=[];const weeks=new Set<string>();for(let i=0;i<STORES.length;i++){for(const r of (data[i]??[]).slice(1)){const date=dateKey(r[1]);if(!date.startsWith(`${year}-`))continue;const category=lob(r[6]),productGroup=String(r[8]??"").trim().toUpperCase().replace(/\s+/g," ");if(productGroup!=="DEVICE"||!category)continue;const week=String(r[3]??"").trim();if(week)weeks.add(week);rows.push({store:STORES[i],date,week,lob:category,qty:num(r[11]),value:num(r[13])})}}return NextResponse.json({year,rows,weeks:[...weeks]},{headers:{"cache-control":"public, max-age=120, stale-while-revalidate=300"}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal membaca LOB Device"},{status:500})}}
