import {NextRequest,NextResponse} from "next/server";
import {getSheetRanges} from "@/lib/google-sheets";

const SALES:Record<string,string>={"2025":"1NnRW70VyrtV8c89_M08gTnOGbtzeldSy8gL-gm4GjJ0","2026":"151Qfrz3RZnDMgZjKOPt5s_aS-zscSiOTCWodbUDWM1k"};
const STORES=["M117","M118","M124","M127","M217","M227","M238","M255","M264"];
function norm(v:unknown){return String(v??"").trim().toUpperCase().replace(/\s+/g," ")}
function num(v:unknown){if(typeof v==="number")return Number.isFinite(v)?v:0;let s=String(v??"").trim();if(!s)return 0;s=s.replace(/RP\s*/ig,"").replace(/\s/g,"");if(/^[-+]?\d{1,3}(\.\d{3})+(,\d+)?$/.test(s))s=s.replace(/\./g,"").replace(",",".");else if(/^[-+]?\d{1,3}(,\d{3})+(\.\d+)?$/.test(s))s=s.replace(/,/g,"");else s=s.replace(/[^0-9.-]/g,"");const x=Number(s);return Number.isFinite(x)?x:0}
function dateKey(v:unknown){if(typeof v==="number"&&v>20000){const d=new Date(Date.UTC(1899,11,30)+v*86400000);return d.toISOString().slice(0,10)}const s=String(v??"").trim();let m=s.match(/^(\d{2})[-/](\d{2})[-/](\d{4})$/);if(m)return `${m[3]}-${m[2]}-${m[1]}`;m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:""}
function lob(v:unknown){const x=norm(v);if(x.includes("IPHONE"))return"iPhone";if(x.includes("IPAD"))return"iPad";if(x==="MAC"||x.includes("MACBOOK"))return"Mac";if(x.includes("APPLE WATCH")||x==="WATCH")return"Apple Watch";return""}
function headerIndex(headers:unknown[],names:string[],fallback:number){const h=headers.map(norm);for(const name of names){const i=h.indexOf(norm(name));if(i>=0)return i}return fallback}
export async function GET(req:NextRequest){const year=req.nextUrl.searchParams.get("year")||"2026";if(!SALES[year])return NextResponse.json({error:"Tahun tidak valid"},{status:400});const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Google Sheets belum dikonfigurasi"},{status:503});try{const data=await getSheetRanges(SALES[year],STORES.map(c=>`'${c}'!A:O`),email,key);const out:any[]=[];const weeks=new Set<string>();const debug:any[]=[];for(let i=0;i<STORES.length;i++){const sheet=(data[i]??[]) as unknown[][];if(!sheet.length)continue;let hi=sheet.findIndex(r=>r.some(v=>norm(v)==="PRODUCT GROUP")&&r.some(v=>norm(v)==="PRODUCT CATEGORY"));if(hi<0)hi=0;const headers=sheet[hi]??[];const ix={date:headerIndex(headers,["Tanggal","Date"],1),week:headerIndex(headers,["Week"],3),category:headerIndex(headers,["Product Category","Category"],6),group:headerIndex(headers,["Product Group","Group"],8),qty:headerIndex(headers,["Qty","Quantity","Unit"],11),value:headerIndex(headers,["Local Amount","Amount","Value"],13)};let deviceRows=0,lobRows=0;for(const r of sheet.slice(hi+1)){const date=dateKey(r[ix.date]);if(!date.startsWith(`${year}-`))continue;const group=norm(r[ix.group]);if(group!=="DEVICE"&&!group.includes("DEVICE"))continue;deviceRows++;const category=lob(r[ix.category]);if(!category)continue;lobRows++;const week=String(r[ix.week]??"").trim();if(week)weeks.add(week);out.push({store:STORES[i],date,week,lob:category,qty:num(r[ix.qty]),value:num(r[ix.value])})}debug.push({store:STORES[i],headerRow:hi+1,columns:ix,deviceRows,lobRows})}return NextResponse.json({year,rows:out,weeks:[...weeks],meta:{rowCount:out.length,debug}},{headers:{"cache-control":"no-store"}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal membaca LOB Device"},{status:500})}}
