"use client";
import {useEffect,useState} from "react";
import {createPortal} from "react-dom";
import {FileText,Upload} from "lucide-react";
type SavedSource={name:string;size:number;type:string;addedAt:string};
const KEY="jakarta1-promo-sources-v1",LETTER="jakarta1-promo-program-letter-v1";
export default function Jakarta1PromoSource(){
 const[host,setHost]=useState<Element|null>(null),[active,setActive]=useState(false),[files,setFiles]=useState<SavedSource[]>([]),[letter,setLetter]=useState("");
 useEffect(()=>{const sync=()=>{const title=document.querySelector("main header b")?.textContent?.trim();setActive(title==="Promo Board");setHost(document.querySelector("main > div.space-y-5"))};sync();const o=new MutationObserver(sync);o.observe(document.body,{subtree:true,childList:true,characterData:true});try{setFiles(JSON.parse(localStorage.getItem(KEY)||"[]"));setLetter(localStorage.getItem(LETTER)||"")}catch{}return()=>o.disconnect()},[]);
 const addFiles=(list:FileList|null)=>{if(!list)return;const next=[...files,...Array.from(list).map(f=>({name:f.name,size:f.size,type:f.type||"document",addedAt:new Date().toISOString()}))].slice(-20);setFiles(next);localStorage.setItem(KEY,JSON.stringify(next))};
 const saveLetter=(v:string)=>{setLetter(v);localStorage.setItem(LETTER,v)};
 if(!active||!host)return null;
 return createPortal(<section className="space-y-4 rounded-2xl border bg-white p-4 shadow-sm sm:p-5"><div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-600">Source Promo</p><h3 className="mt-1 text-xl font-black">Dokumen & Program Letter</h3><p className="mt-1 text-sm text-slate-500">Tambahkan referensi promo di sini agar sumber perubahan program tersusun di Promo Board.</p></div><div className="grid gap-4 lg:grid-cols-2"><label className="flex min-h-40 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50 p-5 text-center hover:border-blue-300 hover:bg-blue-50/40"><Upload className="size-7 text-blue-600"/><b className="mt-2">Upload dokumen promo</b><span className="mt-1 text-xs text-slate-500">PDF, Word, Excel, gambar, atau dokumen pendukung</span><input type="file" multiple className="hidden" accept=".pdf,.doc,.docx,.xls,.xlsx,.png,.jpg,.jpeg,.txt" onChange={e=>addFiles(e.target.files)}/></label><label><span className="mb-2 block text-xs font-black uppercase tracking-wide text-slate-400">Program Letter / Catatan Promo</span><textarea value={letter} onChange={e=>saveLetter(e.target.value)} placeholder="Paste isi program letter atau perubahan promo di sini..." className="min-h-40 w-full rounded-2xl border bg-white p-4 text-sm outline-none focus:border-blue-400"/></label></div>{files.length>0&&<div><div className="mb-2 flex items-center justify-between"><b className="text-sm">Dokumen yang ditambahkan</b><button onClick={()=>{setFiles([]);localStorage.removeItem(KEY)}} className="text-xs font-bold text-rose-600">Hapus daftar</button></div><div className="grid gap-2 md:grid-cols-2">{files.map((f,i)=><div key={`${f.name}-${i}`} className="flex items-center gap-3 rounded-xl border bg-slate-50 p-3"><FileText className="size-5 shrink-0 text-blue-600"/><div className="min-w-0"><p className="truncate text-sm font-bold">{f.name}</p><p className="text-xs text-slate-400">{Math.max(1,Math.round(f.size/1024))} KB</p></div></div>)}</div></div>}<div className="rounded-xl bg-blue-50 p-3 text-xs text-blue-800">Source dan Program Letter tersimpan di browser dashboard. Dokumen yang perlu dirangkum oleh ChatGPT juga harus tersedia di percakapan atau connector yang dapat dibaca.</div></section>,host)
}
