"use client";
import {useEffect,useState} from "react";
import {createPortal} from "react-dom";

const STORES=["M117","M118","M124","M127","M217","M227","M238","M255","M264"];
const MONTHS=["Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember"];
const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const pct=(v:number)=>`${new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(v)}%`;
type YearRow={month:number;total:number;stores:Record<string,number>};
type Payload={sales:string;"2025":YearRow[];"2026":YearRow[];error?:string};

export default function Jakarta1YoYStoreFilter(){
 const[host,setHost]=useState<HTMLElement|null>(null),[store,setStore]=useState("ALL"),[sales,setSales]=useState("ALL"),[payload,setPayload]=useState<Payload|null>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{let cancelled=false,tries=0;const mount=()=>{if(cancelled)return;const h=[...document.querySelectorAll("h3")].find(x=>x.textContent?.trim().startsWith("2025 vs 2026"));if(!h){if(tries++<120)setTimeout(mount,100);return}let el=document.getElementById("jakarta1-yoy-store-filter-host") as HTMLElement|null;if(!el){el=document.createElement("div");el.id="jakarta1-yoy-store-filter-host";el.className="mb-3";h.parentElement?.insertAdjacentElement("afterend",el)}setHost(el)};mount();return()=>{cancelled=true}},[]);
 const syncStore=(value:string)=>{const labels=[...document.querySelectorAll("label")];const areaStore=labels.find(l=>l.querySelector("span")?.textContent?.trim()==="Store"&&l.querySelector("select")?.querySelector('option[value="ALL"]')?.textContent?.includes("All Jakarta 1"))?.querySelector("select") as HTMLSelectElement|null;if(!areaStore)return;const setter=Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,"value")?.set;setter?.call(areaStore,value);areaStore.dispatchEvent(new Event("change",{bubbles:true}))};
 const load=async(mode:string)=>{setBusy(true);try{const r=await fetch(`/api/jakarta1-year-comparison?sales=${mode}`,{cache:"no-store"}),j:Payload=await r.json();if(!r.ok)throw new Error(j.error||"Gagal memuat comparison");setPayload(j)}finally{setBusy(false)}};
 useEffect(()=>{if(sales==="DEVICE")void load("DEVICE");else setPayload(null)},[sales]);
 useEffect(()=>{if(!payload||sales!=="DEVICE")return;const h=[...document.querySelectorAll("h3")].find(x=>x.textContent?.trim().startsWith("2025 vs 2026"));const section=h?.closest("section"),table=section?.querySelector("table");if(!h||!table)return;h.textContent=`2025 vs 2026 • ${store==="ALL"?"All Area":store} • Device Only`;const rows=[...table.querySelectorAll("tbody tr")];rows.forEach((tr,i)=>{const a=payload["2025"]?.[i],b=payload["2026"]?.[i],v25=store==="ALL"?(a?.total??0):(a?.stores?.[store]??0),v26=store==="ALL"?(b?.total??0):(b?.stores?.[store]??0),g=v25?(v26-v25)/v25*100:0,c=tr.querySelectorAll("td");if(c[0])c[0].textContent=MONTHS[i];if(c[1])c[1].textContent=money.format(v25);if(c[2])c[2].textContent=money.format(v26);if(c[3])c[3].textContent=v25?pct(g):"—"});window.dispatchEvent(new Event("jakarta1-yoy-filter-updated"))},[payload,store,sales]);
 const changeStore=(v:string)=>{setStore(v);if(sales==="ALL")syncStore(v)};
 const changeSales=(v:string)=>{setSales(v);if(v==="ALL"){setPayload(null);syncStore(store);setTimeout(()=>window.dispatchEvent(new Event("jakarta1-yoy-filter-updated")),100)}};
 return host?createPortal(<div className="grid max-w-3xl gap-3 sm:grid-cols-2"><label className="block"><span className="mb-1 block text-xs font-black uppercase text-slate-400">Filter Store</span><select value={store} onChange={e=>changeStore(e.target.value)} className="h-11 w-full rounded-xl border bg-white px-3 font-bold"><option value="ALL">All Area</option>{STORES.map(s=><option key={s} value={s}>{s}</option>)}</select><span className="mt-1 block text-xs text-slate-400">All Area atau kode store.</span></label><label className="block"><span className="mb-1 block text-xs font-black uppercase text-slate-400">Filter Sales</span><select value={sales} onChange={e=>changeSales(e.target.value)} className="h-11 w-full rounded-xl border bg-white px-3 font-bold"><option value="ALL">All Product Group</option><option value="DEVICE">Device Only</option></select><span className="mt-1 block text-xs text-slate-400">{busy?"Memuat Device Only…":"Total semua penjualan atau Product Group DEVICES saja."}</span></label></div>,host):null;
}
