import {NextRequest,NextResponse} from "next/server";
import {getSheetRanges} from "@/lib/google-sheets";
const SALES:Record<string,string>={"2025":"1NnRW70VyrtV8c89_M08gTnOGbtzeldSy8gL-gm4GjJ0","2026":"151Qfrz3RZnDMgZjKOPt5s_aS-zscSiOTCWodbUDWM1k"};
const STORES=["M117","M118","M124","M127","M217","M227","M238","M255","M264"],BRANDS=["Medpoin","Hastag","Dino","IGA","iBacks","Handal","Omega","Torras"] as const;
type Row=unknown[];type Brand=typeof BRANDS[number];
const n=(v:unknown)=>{if(typeof v==="number")return Number.isFinite(v)?v:0;const x=Number(String(v??"").replace(/\s/g,"").replace(/\.(?=\d{3}(?:\D|$))/g,"").replace(",",".").replace(/[^0-9.-]/g,""));return Number.isFinite(x)?x:0};
function dk(v:unknown){if(typeof v==="number"&&v>20000)return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10);const s=String(v??"").trim();let m=s.match(/^(\d{2})[-/](\d{2})[-/](\d{4})$/);if(m)return`${m[3]}-${m[2]}-${m[1]}`;m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:""}
const blank=()=>({brands:Object.fromEntries(BRANDS.map(b=>[b,0])) as Record<Brand,number>,qoala:0,telkomsel:0,xl:0,indosat:0});
export async function GET(req:NextRequest){const period=req.nextUrl.searchParams.get("period")||"2026-09";if(!/^(2025|2026)-(0[1-9]|1[0-2])$/.test(period))return NextResponse.json({error:"Periode tidak valid"},{status:400});const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Google Sheets belum dikonfigurasi"},{status:503});try{const raw=await getSheetRanges(SALES[period.slice(0,4)],STORES.map(s=>`'${s}'!A:O`),email,key),by:Record<string,ReturnType<typeof blank>>=Object.fromEntries(STORES.map(s=>[s,blank()]));for(let i=0;i<STORES.length;i++)for(const r of ((raw[i]??[]) as Row[]).slice(1)){if(!dk(r[1]).startsWith(period)||r.some(v=>String(v??"").toUpperCase().includes("VOUCHER")))continue;const a=by[STORES[i]],cat=String(r[6]??"").toUpperCase(),desc=String(r[10]??"").toUpperCase(),qty=Math.max(0,n(r[11])),amt=n(r[13]);for(const b of BRANDS)if(desc.includes(b.toUpperCase()))a.brands[b]+=qty;if(cat.includes("PROTEKSI")||desc.includes("QOALA"))a.qoala+=amt;if(desc.includes("TELKOMSEL")||desc.includes("HALO"))a.telkomsel+=amt;if(desc.includes("XL")||desc.includes("MYPRIO"))a.xl+=amt;if(desc.includes("INDOSAT")||desc.includes("IM3"))a.indosat+=amt}const sumBrand=(b:Brand)=>STORES.reduce((v,s)=>v+by[s].brands[b],0),sum=(k:"qoala"|"telkomsel"|"xl"|"indosat")=>STORES.reduce((v,s)=>v+by[s][k],0);return NextResponse.json({period,stores:STORES,product:BRANDS.map(name=>({name,actual:sumBrand(name)})),vas:[{name:"Qoala",actual:sum("qoala")},{name:"Telkomsel",actual:sum("telkomsel")},{name:"XL",actual:sum("xl")},{name:"Indosat",actual:sum("indosat")}],byStore:by})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal memuat Product/VAS Fokus"},{status:500})}}
