import {NextRequest,NextResponse} from "next/server";
import {getSheetRanges} from "@/lib/google-sheets";
const SALES:Record<string,string>={"2025":"1NnRW70VyrtV8c89_M08gTnOGbtzeldSy8gL-gm4GjJ0","2026":"151Qfrz3RZnDMgZjKOPt5s_aS-zscSiOTCWodbUDWM1k"},MASTER="1BjLDXdi_5BgZCUUJAKba-xYRFf0RDmRTT0FW1be03WE";
const STORES=["M117","M118","M124","M127","M217","M227","M238","M255","M264"],SUPPLIERS=["Medpoin","Hastag","Dino","IGA","iBacks","Handal","Omega","Torras"] as const;
type Row=unknown[];type Supplier=typeof SUPPLIERS[number];type Metric={qty:number;value:number};
const S=(v:unknown)=>String(v??"").trim(),U=(v:unknown)=>S(v).toUpperCase(),K=(v:unknown)=>U(v).replace(/[^A-Z0-9]/g,"");
const n=(v:unknown)=>{if(typeof v==="number")return Number.isFinite(v)?v:0;const x=Number(S(v).replace(/\s/g,"").replace(/\.(?=\d{3}(?:\D|$))/g,"").replace(",",".").replace(/[^0-9.-]/g,""));return Number.isFinite(x)?x:0};
function dk(v:unknown){if(typeof v==="number"&&v>20000)return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10);const s=S(v);let m=s.match(/^(\d{2})[-/](\d{2})[-/](\d{4})$/);if(m)return`${m[3]}-${m[2]}-${m[1]}`;m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:""}
function supplierFromPt(v:unknown):Supplier|""{const x=K(v);if(x.includes("MEDPOIN"))return"Medpoin";if(x.includes("HASTAG"))return"Hastag";if(x.includes("DINO"))return"Dino";if(x.includes("IGA"))return"IGA";if(x.includes("IBACKS"))return"iBacks";if(x.includes("HANDAL"))return"Handal";if(x.includes("OMEGA"))return"Omega";if(x.includes("TORRAS"))return"Torras";return""}
function brandToSupplier(rows:Row[]){const out=new Map<string,Supplier>();if(!rows.length)return out;let header=-1,pt=-1,brandName=-1;for(let i=0;i<Math.min(rows.length,20);i++){const h=rows[i],p=h.findIndex(v=>K(v)==="PTNAME"),b=h.findIndex(v=>K(v)==="BRANDNAME");if(p>=0&&b>=0){header=i;pt=p;brandName=b;break}}if(header<0)return out;for(const r of rows.slice(header+1)){const brand=K(r[brandName]),supplier=supplierFromPt(r[pt]);if(brand&&supplier&&!out.has(brand))out.set(brand,supplier)}return out}
const blank=()=>({brands:Object.fromEntries(SUPPLIERS.map(b=>[b,{qty:0,value:0}])) as Record<Supplier,Metric>,qoala:0,telkomsel:0,xl:0,indosat:0});
export async function GET(req:NextRequest){const period=req.nextUrl.searchParams.get("period")||"2026-09";if(!/^(2025|2026)-(0[1-9]|1[0-2])$/.test(period))return NextResponse.json({error:"Periode tidak valid"},{status:400});const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Google Sheets belum dikonfigurasi"},{status:503});try{const [masterRanges,raw]=await Promise.all([getSheetRanges(MASTER,["'Master Data'!A1:M5000"],email,key),getSheetRanges(SALES[period.slice(0,4)],STORES.map(s=>`'${s}'!A:O`),email,key)]),map=brandToSupplier((masterRanges[0]||[]) as Row[]),by:Record<string,ReturnType<typeof blank>>=Object.fromEntries(STORES.map(s=>[s,blank()]));let mapped=0,unmapped=0;const unmappedBrands=new Set<string>();for(let i=0;i<STORES.length;i++)for(const r of ((raw[i]??[]) as Row[]).slice(1)){if(!dk(r[1]).startsWith(period)||r.some(v=>U(v).includes("VOUCHER")))continue;const a=by[STORES[i]],cat=U(r[6]),salesBrand=K(r[7]),desc=U(r[10]),qty=Math.max(0,n(r[11])),amt=n(r[13]),supplier=map.get(salesBrand)||"";if(supplier){a.brands[supplier].qty+=qty;a.brands[supplier].value+=amt;mapped++}else if(salesBrand){unmapped++;if(unmappedBrands.size<30)unmappedBrands.add(S(r[7]))}if(cat.includes("PROTEKSI")||desc.includes("QOALA"))a.qoala+=amt;if(desc.includes("TELKOMSEL")||desc.includes("HALO"))a.telkomsel+=amt;if(desc.includes("XL")||desc.includes("MYPRIO"))a.xl+=amt;if(desc.includes("INDOSAT")||desc.includes("IM3"))a.indosat+=amt}const sumSupplier=(b:Supplier,k:keyof Metric)=>STORES.reduce((v,s)=>v+by[s].brands[b][k],0),sum=(k:"qoala"|"telkomsel"|"xl"|"indosat")=>STORES.reduce((v,s)=>v+by[s][k],0);return NextResponse.json({period,stores:STORES,product:SUPPLIERS.map(name=>({name,qty:sumSupplier(name,"qty"),value:sumSupplier(name,"value")})),vas:[{name:"Qoala",actual:sum("qoala")},{name:"Telkomsel",actual:sum("telkomsel")},{name:"XL",actual:sum("xl")},{name:"Indosat",actual:sum("indosat")}],byStore:by,meta:{mapping:"Sales Brand -> Master Data Brand Name -> PT Name -> 3PP supplier",masterBrandMappings:map.size,mapped3ppRows:mapped,unmappedSalesRows:unmapped,unmappedBrandSample:[...unmappedBrands],source:"Actual sales by selected month; brand-to-supplier mapping"}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal memuat Product/VAS Fokus"},{status:500})}}
