import {NextRequest,NextResponse} from "next/server";
import {getSheetRanges} from "@/lib/google-sheets";
const SALES:Record<string,string>={"2025":"1NnRW70VyrtV8c89_M08gTnOGbtzeldSy8gL-gm4GjJ0","2026":"151Qfrz3RZnDMgZjKOPt5s_aS-zscSiOTCWodbUDWM1k"},MASTER="1BjLDXdi_5BgZCUUJAKba-xYRFf0RDmRTT0FW1be03WE";
const STORES=["M117","M118","M124","M127","M217","M227","M238","M255","M264"],BRANDS=["Medpoin","Hastag","Dino","IGA","iBacks","Handal","Omega","Torras"] as const;
type Row=unknown[];type Brand=typeof BRANDS[number];type Metric={qty:number;value:number};
const S=(v:unknown)=>String(v??"").trim(),U=(v:unknown)=>S(v).toUpperCase(),K=(v:unknown)=>U(v).replace(/[^A-Z0-9]/g,"");
const n=(v:unknown)=>{if(typeof v==="number")return Number.isFinite(v)?v:0;const x=Number(S(v).replace(/\s/g,"").replace(/\.(?=\d{3}(?:\D|$))/g,"").replace(",",".").replace(/[^0-9.-]/g,""));return Number.isFinite(x)?x:0};
function dk(v:unknown){if(typeof v==="number"&&v>20000)return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10);const s=S(v);let m=s.match(/^(\d{2})[-/](\d{2})[-/](\d{4})$/);if(m)return`${m[3]}-${m[2]}-${m[1]}`;m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:""}
function brand(v:unknown):Brand|""{const x=K(v);return BRANDS.find(b=>x.includes(K(b)))||""}
function supplierMap(rows:Row[]){const out=new Map<string,Brand>();for(let i=0;i<Math.min(rows.length,100);i++){const h=rows[i],article=h.findIndex(v=>["ARTICLENUMBER","ARTICLE","SAPARTICLE","PRODUCTCODE","SKU"].includes(K(v))),supplier=h.findIndex(v=>["SUPPLIER","SUPPLIERNAME","VENDOR","VENDORNAME","BRAND"].includes(K(v)));if(article<0||supplier<0)continue;for(const r of rows.slice(i+1)){const a=U(r[article]),b=brand(r[supplier]);if(a&&b)out.set(a,b)}if(out.size)break}return out}
const blank=()=>({brands:Object.fromEntries(BRANDS.map(b=>[b,{qty:0,value:0}])) as Record<Brand,Metric>,qoala:0,telkomsel:0,xl:0,indosat:0});
export async function GET(req:NextRequest){const period=req.nextUrl.searchParams.get("period")||"2026-09";if(!/^(2025|2026)-(0[1-9]|1[0-2])$/.test(period))return NextResponse.json({error:"Periode tidak valid"},{status:400});const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Google Sheets belum dikonfigurasi"},{status:503});try{const [masterRanges,raw]=await Promise.all([getSheetRanges(MASTER,["'Master Data'!A1:AZ5000"],email,key),getSheetRanges(SALES[period.slice(0,4)],STORES.map(s=>`'${s}'!A:O`),email,key)]),suppliers=supplierMap((masterRanges[0]||[]) as Row[]),by:Record<string,ReturnType<typeof blank>>=Object.fromEntries(STORES.map(s=>[s,blank()]));for(let i=0;i<STORES.length;i++)for(const r of ((raw[i]??[]) as Row[]).slice(1)){if(!dk(r[1]).startsWith(period)||r.some(v=>U(v).includes("VOUCHER")))continue;const a=by[STORES[i]],article=U(r[9]),cat=U(r[6]),desc=U(r[10]),qty=Math.max(0,n(r[11])),amt=n(r[13]),b=suppliers.get(article)||brand(desc);if(b){a.brands[b].qty+=qty;a.brands[b].value+=amt}if(cat.includes("PROTEKSI")||desc.includes("QOALA"))a.qoala+=amt;if(desc.includes("TELKOMSEL")||desc.includes("HALO"))a.telkomsel+=amt;if(desc.includes("XL")||desc.includes("MYPRIO"))a.xl+=amt;if(desc.includes("INDOSAT")||desc.includes("IM3"))a.indosat+=amt}const sumBrand=(b:Brand,k:keyof Metric)=>STORES.reduce((v,s)=>v+by[s].brands[b][k],0),sum=(k:"qoala"|"telkomsel"|"xl"|"indosat")=>STORES.reduce((v,s)=>v+by[s][k],0);return NextResponse.json({period,stores:STORES,product:BRANDS.map(name=>({name,qty:sumBrand(name,"qty"),value:sumBrand(name,"value")})),vas:[{name:"Qoala",actual:sum("qoala")},{name:"Telkomsel",actual:sum("telkomsel")},{name:"XL",actual:sum("xl")},{name:"Indosat",actual:sum("indosat")}],byStore:by,meta:{supplierLookup:!!suppliers.size,supplierArticles:suppliers.size,source:"Compile sales + Master Data supplier lookup"}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal memuat Product/VAS Fokus"},{status:500})}}
