import {NextRequest,NextResponse} from "next/server";
import {getSheetRanges} from "@/lib/google-sheets";

const SALES:Record<string,string>={"2025":"1NnRW70VyrtV8c89_M08gTnOGbtzeldSy8gL-gm4GjJ0","2026":"151Qfrz3RZnDMgZjKOPt5s_aS-zscSiOTCWodbUDWM1k"};
const STORES=["M132","M118","M124","M127","M217","M227","M238","M255","M264"];
function n(v:unknown){if(typeof v==="number")return Number.isFinite(v)?v:0;const s=String(v??"").trim();if(!s)return 0;const x=Number(s.replace(/\s/g,"").replace(/\.(?=\d{3}(?:\D|$))/g,"").replace(",",".").replace(/[^0-9.-]/g,""));return Number.isFinite(x)?x:0}
function dateKey(v:unknown){if(typeof v==="number"&&v>20000){const d=new Date(Date.UTC(1899,11,30)+v*86400000);return d.toISOString().slice(0,10)}const s=String(v??"").trim();let m=s.match(/^(\d{2})[-/](\d{2})[-/](\d{4})$/);if(m)return `${m[3]}-${m[2]}-${m[1]}`;m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:""}
function voucher(row:unknown[]){return row.some(v=>String(v??"").toUpperCase().includes("VOUCHER"))}
export async function GET(req:NextRequest){const mode=req.nextUrl.searchParams.get("sales")==="DEVICE"?"DEVICE":"ALL",email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Google Sheets belum dikonfigurasi"},{status:503});try{const result:Record<string,unknown>={};for(const year of ["2025","2026"]){const ranges=await getSheetRanges(SALES[year],STORES.map(c=>`'${c}'!A:O`),email,key),months=Array.from({length:12},()=>Object.fromEntries(STORES.map(c=>[c,0])) as Record<string,number>);for(let si=0;si<STORES.length;si++){for(const row of (ranges[si]??[]).slice(1) as unknown[][]){const d=dateKey(row[1]);if(!d.startsWith(`${year}-`)||voucher(row))continue;const group=String(row[8]??"").trim().toUpperCase();if(mode==="DEVICE"&&group!=="DEVICE"&&group!=="DEVICES")continue;const mi=Number(d.slice(5,7))-1;if(mi>=0&&mi<12)months[mi][STORES[si]]+=n(row[13])}}result[year]=months.map((stores,i)=>({month:i+1,total:STORES.reduce((a,c)=>a+(stores[c]||0),0),stores}))}return NextResponse.json({sales:mode,...result},{headers:{"cache-control":"public, max-age=300, stale-while-revalidate=600"}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal membaca year comparison"},{status:500})}}
