"use client";
import {useEffect,useMemo,useState} from "react";
import {ArrowLeft,Boxes,CalendarRange,RefreshCw,Store as StoreIcon,TrendingDown,TrendingUp} from "lucide-react";

type Row={y2025:number;y2026:number;qty2025:number;qty2026:number;gap:number;yoy:number|null;qtyYoy?:number|null};
type StoreRow=Row&{code:string;name:string};type MonthRow=Row&{month:number;label:string};type LobRow=Row&{lob:string};type LobMonth={month:number;label:string;rows:LobRow[]};
type Payload={summary:Row&{growthStores:number;disgrowthStores:number};stores:StoreRow[];months:MonthRow[];lobs:LobRow[];detail:Record<string,{months:MonthRow[];lobs:LobRow[];lobMonthly:LobMonth[]}>;meta:{scope:string;label?:string;includedLobs:string[];excluded:string[];source?:string};error?:string};
const months=["Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember"];
const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});const num=new Intl.NumberFormat("id-ID");
const pct=(v:number|null|undefined)=>v==null?"—":`${v>=0?"+":""}${v.toFixed(1)}%`;const tone=(v:number|null|undefined)=>v==null?"text-slate-500":v<0?"text-rose-600":"text-emerald-600";
const th="whitespace-nowrap px-3 py-3 text-left text-[11px] font-black uppercase tracking-wide text-slate-400",td="whitespace-nowrap px-3 py-3";
function Card({label,value,sub,icon}:{label:string;value:string;sub?:string;icon?:React.ReactNode}){return <div className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.12em] text-slate-400">{label}</p><p className="mt-2 text-xl font-black">{value}</p>{sub&&<p className="mt-2 text-xs text-slate-500">{sub}</p>}</div>{icon&&<div className="rounded-xl bg-blue-50 p-2 text-blue-600">{icon}</div>}</div></div>}
function Table({children}:{children:React.ReactNode}){return <div className="overflow-x-auto rounded-2xl border bg-white shadow-sm"><table className="w-full text-sm">{children}</table></div>}

export default function YoYAppleDevicePage(){
 const[scope,setScope]=useState<"all"|"device">("device"),[endMonth,setEndMonth]=useState(9),[store,setStore]=useState("ALL"),[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[refreshKey,setRefreshKey]=useState(0);
 useEffect(()=>{setLoading(true);setError("");fetch(`/api/jakarta1-yoy-device?scope=${scope}&endMonth=${endMonth}&r=${refreshKey}`,{cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||"Gagal memuat data");setData(j)}).catch(e=>setError(e instanceof Error?e.message:"Gagal memuat data")).finally(()=>setLoading(false))},[scope,endMonth,refreshKey]);
 const selected=store==="ALL"?null:data?.stores.find(s=>s.code===store);const summary=selected??data?.summary;const monthsRows=selected?data?.detail[store]?.months:data?.months;const lobRows=selected?data?.detail[store]?.lobs:data?.lobs;const lobMonthly=selected?data?.detail[store]?.lobMonthly??[]:[];const sortedStores=useMemo(()=>data?.stores.slice().sort((a,b)=>a.code.localeCompare(b.code))??[],[data]);
 return <div className="min-h-screen bg-slate-50 text-slate-950"><header className="sticky top-0 z-30 border-b bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-3 px-4 py-3 sm:px-7"><div className="flex items-center gap-3"><a href="/" className="rounded-xl border bg-white p-2"><ArrowLeft className="size-5"/></a><div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-600">Jakarta 1 • Reporting</p><h1 className="text-xl font-black">YoY Performance</h1></div></div><button onClick={()=>setRefreshKey(x=>x+1)} className="flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-sm font-bold"><RefreshCw className={`size-4 ${loading?"animate-spin":""}`}/>Perbarui</button></div></header><main className="mx-auto max-w-[1500px] space-y-5 p-4 sm:p-7">
 <div className="inline-flex rounded-2xl border bg-white p-1 shadow-sm"><button onClick={()=>{setScope("all");setStore("ALL")}} className={`rounded-xl px-4 py-2 text-sm font-black ${scope==="all"?"bg-slate-900 text-white":"text-slate-500"}`}>All Value</button><button onClick={()=>{setScope("device");setStore("ALL")}} className={`rounded-xl px-4 py-2 text-sm font-black ${scope==="device"?"bg-blue-600 text-white":"text-slate-500"}`}>Device Only</button></div>
 <section className="rounded-3xl bg-gradient-to-br from-[#0872b9] to-[#075b97] p-5 text-white shadow-lg"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-100">{scope==="device"?"Device Only":"All Value"}</p><h2 className="mt-2 text-3xl font-black">Year on Year Performance</h2><p className="mt-2 text-sm text-blue-100">{scope==="device"?"Hanya iPhone, MacBook, iPad dan Apple Watch. Accessories, VAS dan AirPods tidak termasuk.":"Total value Jakarta 1 dari source existing."}</p></div><div className="grid gap-3 sm:grid-cols-2"><label><span className="mb-1 block text-xs font-black uppercase text-blue-100">Periode YTD s.d.</span><select value={endMonth} onChange={e=>setEndMonth(Number(e.target.value))} className="h-11 min-w-52 rounded-xl bg-white px-3 font-bold text-slate-900">{months.map((m,i)=><option key={m} value={i+1}>Jan–{m} 2026 vs 2025</option>)}</select></label><label><span className="mb-1 block text-xs font-black uppercase text-blue-100">Store</span><select value={store} onChange={e=>setStore(e.target.value)} className="h-11 min-w-60 rounded-xl bg-white px-3 font-bold text-slate-900"><option value="ALL">All Jakarta 1</option>{sortedStores.map(s=><option key={s.code} value={s.code}>{s.code} - {s.name}</option>)}</select></label></div></div></section>
 {error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-4 font-bold text-rose-700">{error}</div>}
 {loading&&!data?<div className="grid min-h-[40vh] place-items-center"><RefreshCw className="size-8 animate-spin text-blue-600"/></div>:data&&summary?<><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Card label="YTD 2026" value={money.format(summary.y2026)} icon={<CalendarRange className="size-5"/>}/><Card label="YTD 2025" value={money.format(summary.y2025)} icon={<CalendarRange className="size-5"/>}/><Card label="YoY Growth" value={pct(summary.yoy)} sub={`Gap ${money.format(summary.gap)}`} icon={(summary.yoy??0)<0?<TrendingDown className="size-5"/>:<TrendingUp className="size-5"/>}/>{scope==="device"&&<Card label="Qty Growth" value={pct(summary.qtyYoy)} sub={`${num.format(summary.qty2025)} → ${num.format(summary.qty2026)} unit`} icon={<Boxes className="size-5"/>}/>} {!selected&&<Card label="Store Status" value={`${data.summary.disgrowthStores} Disgrowth`} sub={`${data.summary.growthStores} Growth`} icon={<StoreIcon className="size-5"/>}/>}</div>
 {!selected&&<section><h3 className="mb-3 text-xl font-black">Store Dragging Performance</h3><Table><thead><tr><th className={th}>Rank</th><th className={th}>Store</th><th className={th}>2025</th><th className={th}>2026</th><th className={th}>Gap</th><th className={th}>YoY</th></tr></thead><tbody>{data.stores.map((r,i)=><tr className="border-t" key={r.code}><td className={`${td} font-black`}>{i+1}</td><td className={`${td} font-bold`}>{r.code} • {r.name}</td><td className={td}>{money.format(r.y2025)}</td><td className={td}>{money.format(r.y2026)}</td><td className={`${td} font-black ${tone(r.gap)}`}>{money.format(r.gap)}</td><td className={`${td} font-black ${tone(r.yoy)}`}>{pct(r.yoy)}</td></tr>)}</tbody></Table></section>}
 <section className="grid gap-5 xl:grid-cols-2"><div><h3 className="mb-3 text-xl font-black">Monthly YoY {selected?`• ${selected.code}`:"• Jakarta 1"}</h3><Table><thead><tr><th className={th}>Bulan</th><th className={th}>2025</th><th className={th}>2026</th><th className={th}>Gap</th><th className={th}>YoY</th></tr></thead><tbody>{monthsRows?.map(r=><tr className="border-t" key={r.month}><td className={`${td} font-bold`}>{r.label}</td><td className={td}>{money.format(r.y2025)}</td><td className={td}>{money.format(r.y2026)}</td><td className={`${td} font-bold ${tone(r.gap)}`}>{money.format(r.gap)}</td><td className={`${td} font-black ${tone(r.yoy)}`}>{pct(r.yoy)}</td></tr>)}</tbody></Table></div>{scope==="device"&&<div><h3 className="mb-3 text-xl font-black">LOB Growth / Disgrowth</h3><Table><thead><tr><th className={th}>LOB</th><th className={th}>2025</th><th className={th}>2026</th><th className={th}>Gap</th><th className={th}>YoY</th></tr></thead><tbody>{lobRows?.map(r=><tr className="border-t" key={r.lob}><td className={`${td} font-bold`}>{r.lob}</td><td className={td}>{money.format(r.y2025)}</td><td className={td}>{money.format(r.y2026)}</td><td className={`${td} font-black ${tone(r.gap)}`}>{money.format(r.gap)}</td><td className={`${td} font-black ${tone(r.yoy)}`}>{pct(r.yoy)}</td></tr>)}</tbody></Table></div>}</section>
 {scope==="device"&&selected&&lobMonthly.length>0&&<section><div className="mb-3"><h3 className="text-xl font-black">Detail LOB per Bulan • {selected.code}</h3><p className="text-sm text-slate-500">Compare per LOB setiap bulan: Sales, Qty, Growth/Disgrowth vs bulan yang sama tahun lalu.</p></div><div className="grid gap-4 lg:grid-cols-2">{lobMonthly.map(m=>{const total=monthsRows?.find(x=>x.month===m.month);const driver=[...m.rows].sort((a,b)=>a.gap-b.gap)[0];return <div key={m.month} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3 border-b pb-3"><div><p className="text-xs font-black uppercase tracking-[.15em] text-slate-400">{m.label} 2026 vs 2025</p><p className="mt-1 text-lg font-black">Total Device <span className={tone(total?.yoy)}>{pct(total?.yoy)}</span></p></div>{total&&<div className="text-right text-xs text-slate-500"><div>{money.format(total.y2025)} → {money.format(total.y2026)}</div><div>{num.format(total.qty2025)} → {num.format(total.qty2026)} unit</div></div>}</div><div className="mt-3 space-y-2">{m.rows.map(r=>{const mixed=(r.yoy??0)*(r.qtyYoy??0)<0;const status=mixed?"Mix":(r.yoy??0)<0?"Disgrowth":"Growth";return <div key={r.lob} className="rounded-xl bg-slate-50 p-3"><div className="flex items-center justify-between gap-3"><b>{r.lob}</b><span className={`rounded-full px-2 py-1 text-xs font-black ${mixed?"bg-amber-100 text-amber-700":(r.yoy??0)<0?"bg-rose-100 text-rose-700":"bg-emerald-100 text-emerald-700"}`}>{status}</span></div><div className="mt-2 grid grid-cols-2 gap-2 text-xs"><div><span className="text-slate-400">Sales</span><div className="font-bold">{money.format(r.y2025)} → {money.format(r.y2026)}</div><div className={`font-black ${tone(r.yoy)}`}>{pct(r.yoy)}</div></div><div><span className="text-slate-400">Qty</span><div className="font-bold">{num.format(r.qty2025)} → {num.format(r.qty2026)} unit</div><div className={`font-black ${tone(r.qtyYoy)}`}>{pct(r.qtyYoy)}</div></div></div></div>})}</div>{driver&&<div className="mt-3 rounded-xl bg-rose-50 px-3 py-2 text-xs text-rose-700"><b>Driver bulan ini:</b> {driver.lob} • {money.format(driver.gap)} ({pct(driver.yoy)})</div>}</div>})}</div></section>}
 </>:null}</main></div>}
