import {NextRequest,NextResponse} from "next/server";
import {getSheetRanges} from "@/lib/google-sheets";
import {JAKARTA1_STORES} from "@/lib/jakarta1-stores";
const SALES:Record<string,string>={"2025":"1NnRW70VyrtV8c89_M08gTnOGbtzeldSy8gL-gm4GjJ0","2026":"151Qfrz3RZnDMgZjKOPt5s_aS-zscSiOTCWodbUDWM1k"};
const MASTER="1BjLDXdi_5BgZCUUJAKba-xYRFf0RDmRTT0FW1be03WE";
type R=unknown[];type Item={product:string;category:string;group:string};type A={lob:Record<string,number>;products:Record<string,Record<string,number>>;staff:Record<string,Record<string,number>>};
const S=(v:unknown)=>String(v??"").trim(),U=(v:unknown)=>S(v).toUpperCase(),K=(v:unknown)=>U(v).replace(/[^A-Z0-9]/g,"");
const N=(v:unknown)=>{if(typeof v==="number")return Number.isFinite(v)?v:0;const x=Number(String(v??0).replace(/\./g,"").replace(",",".").replace(/[^0-9.-]/g,""));return Number.isFinite(x)?x:0};
function col(h:R,n:string[]){const z=n.map(K);return h.findIndex(v=>z.includes(K(v)))}
function dk(v:unknown){if(typeof v==="number"&&v>20000)return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10);const x=S(v);let m=x.match(/^(\d{2})[-/](\d{2})[-/](\d{4})$/);if(m)return`${m[3]}-${m[2]}-${m[1]}`;m=x.match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:""}
function deviceGroup(v:string){const x=K(v);return x==="DEVICE"||x==="DEVICES"}
function lobFromCategory(category:string){const x=U(category);if(x.includes("IPHONE"))return"iPhone";if(x.includes("MACBOOK")||x==="MAC"||x.startsWith("MAC "))return"MacBook";if(x.includes("IPAD"))return"iPad";if(x.includes("APPLE WATCH")||x==="WATCH"||x.startsWith("WATCH "))return"Apple Watch";if(x.includes("AIRPODS")||x.includes("AIRPOD"))return"AirPods";return""}
function add(m:Record<string,number>,k:string,v:number){if(k)m[k]=(m[k]||0)+v}
function master(rows:R[]){const items=new Map<string,Item>();for(let i=0;i<Math.min(100,rows.length);i++){const h=rows[i],a=col(h,["ARTICLE NUMBER","ARTICLE","SAP ARTICLE","PRODUCT CODE","SKU"]),p=col(h,["PRODUCT","PRODUCT NAME","DESCRIPTION"]);if(a<0||p<0)continue;const c=col(h,["CATEGORY","PRODUCT CATEGORY"]),g=col(h,["LOB","PRODUCT GROUP"]);for(const r of rows.slice(i+1)){const ar=U(r[a]);if(ar)items.set(ar,{product:S(r[p]),category:c>=0?S(r[c]):"",group:g>=0?S(r[g]):""})}break}return{stores:JAKARTA1_STORES,items}}
function parse(rows:R[],period:string,mode:string,week:string,start:string,end:string,items:Map<string,Item>){const out:A={lob:{},products:{},staff:{}},weeks=new Set<string>();if(!rows.length)return{out,weeks};let hi=-1;for(let i=0;i<Math.min(30,rows.length);i++){if(col(rows[i],["TANGGAL","DATE"])>=0&&col(rows[i],["WEEK"])>=0&&col(rows[i],["QTY","QUANTITY"])>=0){hi=i;break}}if(hi<0)throw new Error("Header Tanggal / Week / Qty Data Compile tidak ditemukan");const h=rows[hi],x={d:col(h,["TANGGAL","DATE"]),w:col(h,["WEEK"]),sid:col(h,["EMPLOYEE NUMBER","EMPLOYEE"]),sn:col(h,["NAMA STAFF","STAFF NAME"]),cat:col(h,["PRODUCT CATEGORY","CATEGORY"]),grp:col(h,["PRODUCT GROUP","LOB","GROUP"]),art:col(h,["ARTICLE NUMBER","ARTICLE","SAP ARTICLE","PRODUCT CODE","SKU"]),des:col(h,["DESCRIPTION","PRODUCT","PRODUCT NAME"]),q:col(h,["QTY","QUANTITY"])};for(const r of rows.slice(hi+1)){const d=dk(r[x.d]),w=S(r[x.w]);if(d.startsWith(period)&&w)weeks.add(w);const ok=mode==="range"?!!d&&d>=start&&d<=end:mode==="week"?d.startsWith(period)&&w===week:d.startsWith(period);if(!ok)continue;const q=N(r[x.q]);if(q<=0)continue;const mi=x.art>=0?items.get(U(r[x.art])):undefined;const category=mi?.category||(x.cat>=0?S(r[x.cat]):"");const group=mi?.group||(x.grp>=0?S(r[x.grp]):"");if(!deviceGroup(group))continue;const l=lobFromCategory(category);if(!l)continue;const des=mi?.product||(x.des>=0?S(r[x.des]):"");add(out.lob,l,q);out.products[l]??={};add(out.products[l],des||U(r[x.art]),q);const staff=(x.sn>=0?S(r[x.sn]):"")||(x.sid>=0?S(r[x.sid]):"");if(staff){out.staff[l]??={};add(out.staff[l],staff,q)}}return{out,weeks}}
function weekSort(a:string,b:string){const pa=a.match(/Week\s*(\d+)\s*Q(\d+)/i),pb=b.match(/Week\s*(\d+)\s*Q(\d+)/i);if(pa&&pb){const qa=Number(pa[2]),qb=Number(pb[2]);return qa===qb?Number(pa[1])-Number(pb[1]):qa-qb}return a.localeCompare(b,undefined,{numeric:true})}
export async function GET(req:NextRequest){const p=req.nextUrl.searchParams,period=p.get("period")||"2026-09",mode=p.get("mode")||"month",week=p.get("week")||"",start=p.get("start")||"",end=p.get("end")||"";if(!/^(2025|2026)-(0[1-9]|1[0-2])$/.test(period))return NextResponse.json({error:"Periode tidak valid"},{status:400});const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Google Sheets belum dikonfigurasi"},{status:503});try{const [mr]=await getSheetRanges(MASTER,["'Master Data'!A1:AZ5000"],email,key),m=master((mr||[]) as R[]);const raw=await getSheetRanges(SALES[period.slice(0,4)],m.stores.map(s=>`'${s.code}'!A:O`),email,key),byStore:Record<string,A>={},weeks=new Set<string>();m.stores.forEach((st,i)=>{const z=parse((raw[i]||[]) as R[],period,mode,week,start,end,m.items);byStore[st.code]=z.out;z.weeks.forEach(w=>weeks.add(w))});const lobs=["iPhone","MacBook","iPad","Apple Watch","AirPods"],area=Object.fromEntries(lobs.map(l=>[l,m.stores.reduce((a,s)=>a+(byStore[s.code].lob[l]||0),0)]));const storeRows=m.stores.map(s=>({code:s.code,name:s.name,actual:byStore[s.code].lob,target:null}));const products=Object.fromEntries(lobs.map(l=>[l,Object.entries(m.stores.reduce((acc,s)=>{for(const[k,v]of Object.entries(byStore[s.code].products[l]||{}))acc[k]=(acc[k]||0)+v;return acc},{} as Record<string,number>)).sort((a,b)=>b[1]-a[1]).map(([name,actual])=>({name,actual,target:null}))]));const staff=Object.fromEntries(m.stores.map(s=>[s.code,Object.fromEntries(lobs.map(l=>[l,Object.entries(byStore[s.code].staff[l]||{}).sort((a,b)=>b[1]-a[1]).map(([name,actual])=>({name,actual}))]))]));return NextResponse.json({period,mode,weeks:[...weeks].sort(weekSort),stores:m.stores,lobs:lobs.map(name=>({name,actual:area[name],target:null})),storeRows,products,staff,byStore,meta:{actualMetric:"Qty / Unit",weekSource:"Data Compile column Week",deviceOnly:true,deviceRule:"Product Group DEVICE + Product Category",targetNote:"Actual LOB hanya Product Group DEVICE. Category: iPhone, Mac, iPad, Apple Watch, AirPods. Target Qty hanya ditampilkan bila konfigurasi target valid tersedia."}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal memuat LOB Target Fokus"},{status:500})}}
